//! Tests against real-world RTF files from open-source projects.
//!
//! These files were generated by actual RTF producers (Word, LibreOffice,
//! macOS TextEdit, Google Docs, Apple Pages, etc.) and exercise features
//! that hand-crafted test files miss.
//!
//! Sources (all permissively licensed):
//! - rtf2xml (MIT): paulhtremblay/rtf2xml
//! - RtfPipe (MIT): erdomke/RtfPipe
//! - rtfparserkit (Apache-2.0): joniles/rtfparserkit
//! - striprtf (BSD-3-Clause): joshy/striprtf

use udoc_core::backend::{FormatBackend, PageExtractor};

fn real_world_dir() -> std::path::PathBuf {
    std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/corpus/real-world")
}

/// Open a real-world RTF file and extract text from page 0.
fn extract(name: &str) -> String {
    let path = real_world_dir().join(name);
    let mut doc =
        udoc_rtf::RtfDocument::open(&path).unwrap_or_else(|e| panic!("failed to open {name}: {e}"));
    assert_eq!(doc.page_count(), 1);
    let mut page = doc.page(0).expect("page 0");
    page.text().expect("text()")
}

/// Open a real-world RTF file and return the document (for metadata/table tests).
fn open(name: &str) -> udoc_rtf::RtfDocument {
    let path = real_world_dir().join(name);
    udoc_rtf::RtfDocument::open(&path).unwrap_or_else(|e| panic!("failed to open {name}: {e}"))
}

// ---- Producer diversity: no panics, produces non-empty text -----------------

#[test]
fn openoffice_hello_world() {
    let text = extract("rtf2xml_open_office.rtf");
    assert_eq!(text.trim(), "Hello world.");
}

#[test]
fn textedit_mixed_fonts() {
    let text = extract("rtf2xml_textedit_mixed.rtf");
    // macOS TextEdit uses \<newline> for paragraph breaks instead of \par.
    assert!(text.contains("Normal text"), "got: {text}");
    assert!(text.contains("bold"), "got: {text}");
    // Verify paragraph breaks are present (not all on one line).
    assert!(text.lines().count() > 1, "should have multiple paragraphs");
}

#[test]
fn textedit_hyperlink() {
    let text = extract("striprtf_textedit_hyperlink.rtf");
    assert!(text.contains("striprtf.dev"), "got: {text}");
    assert!(text.contains("github"), "got: {text}");
}

#[test]
fn google_docs_list() {
    let text = extract("rtfpipe_list_google.rtf");
    assert!(text.contains("Paragraph"), "got: {text}");
    assert!(text.contains("Bullet"), "got: {text}");
}

#[test]
fn apple_pages_table() {
    let text = extract("striprtf_pages_table.rtf");
    assert!(!text.is_empty());
    assert!(text.contains("normaler Text"), "got: {text}");
}

// ---- Hyperlink / field text extraction --------------------------------------

#[test]
fn hyperlink_field_text() {
    // \fldrslt content should appear in extracted text.
    let text = extract("rtf2xml_hyperlink.rtf");
    assert!(text.contains("http://www.cnn.com/"), "got: {text}");
    assert!(text.contains("mailto:"), "got: {text}");
    assert!(text.contains("Hyperlink within doc"), "got: {text}");
}

// ---- Encoding / international text ------------------------------------------

#[test]
fn japanese_text() {
    let text = extract("rtf2xml_japanese.rtf");
    // Japanese text should be present (NeoOffice-generated document).
    assert!(
        text.contains("NeoOffice"),
        "expected NeoOffice reference, got: {}",
        &text[..text.len().min(200)]
    );
    // Should contain actual Japanese characters.
    assert!(
        text.chars().any(|c| ('\u{3040}'..='\u{30FF}').contains(&c)),
        "expected hiragana/katakana characters"
    );
}

#[test]
fn cp950_traditional_chinese() {
    let text = extract("rtfparserkit_cp950.rtf");
    assert!(text.contains("Test Text"), "got: {text}");
    assert!(text.contains("Copyright"), "got: {text}");
}

#[test]
fn multibyte_hex_japanese() {
    let text = extract("rtfparserkit_multibyte_hex.rtf");
    // Should decode multi-byte hex escapes into Japanese text.
    assert!(
        text.chars().any(|c| ('\u{3040}'..='\u{9FFF}').contains(&c)),
        "expected CJK characters, got: {text}"
    );
}

#[test]
fn negative_unicode_escapes() {
    let text = extract("rtfparserkit_negative_unicode.rtf");
    // File contains \u escapes with negative values for PUA codepoints.
    assert!(text.contains("F700"), "got: {text}");
}

#[test]
fn french_accented_text() {
    let text = extract("striprtf_french.rtf");
    assert!(!text.is_empty());
}

#[test]
fn ansicpg1250_central_european() {
    let text = extract("striprtf_ansicpg1250.rtf");
    // Polish text with CP1250 encoding.
    assert!(
        text.contains("Zgodnie"),
        "expected Polish text, got: {}",
        &text[..text.len().min(200)]
    );
}

#[test]
fn table_simple_real_world() {
    let text = extract("rtf2xml_table_simple.rtf");
    assert!(text.contains("2 X 2 Table"), "got: {text}");
}

#[test]
fn merged_cells_real_world() {
    let mut doc = open("rtfpipe_merged_cells.rtf");
    let mut page = doc.page(0).expect("page 0");
    let tables = page.tables().expect("tables()");
    assert!(!tables.is_empty(), "should have at least one table");
    // The file has both vertical and horizontal merged cells.
    // All text is inside table cells, so check cell content.
    let all_cell_text: String = tables
        .iter()
        .flat_map(|t| &t.rows)
        .flat_map(|r| &r.cells)
        .map(|c| c.text.as_str())
        .collect::<Vec<_>>()
        .join(" ");
    assert!(
        all_cell_text.contains("merged cells"),
        "got: {all_cell_text}"
    );
}

#[test]
fn nested_table_no_panic() {
    // Nested tables are not fully supported but must not panic.
    let text = extract("rtfpipe_nested_table.rtf");
    assert!(!text.is_empty());
}

#[test]
fn word_list() {
    let text = extract("rtfpipe_list_word.rtf");
    assert!(text.contains("Paragraph"), "got: {text}");
    assert!(text.contains("Bullet"), "got: {text}");
}

#[test]
fn headings_mixed() {
    let text = extract("rtf2xml_headings.rtf");
    assert!(text.contains("Heading one"), "got: {text}");
}

// ---- Symbol font ------------------------------------------------------------

#[test]
fn symbol_font_unicode_escapes() {
    let text = extract("rtf2xml_symbol.rtf");
    // The file uses \u-NNNN for Greek letters (PUA codepoints).
    // Verify the surrounding ASCII text is extracted correctly.
    assert!(text.contains("GREEK CAPITAL LETTER ALPHA"), "got: {text}");
    assert!(text.contains(":0391"), "got: {text}");
    // The PUA characters (U+F041 etc.) should be present in the output.
    assert!(
        text.chars().any(|c| ('\u{F000}'..='\u{F0FF}').contains(&c)),
        "expected Private Use Area characters from Symbol font"
    );
}

// ---- \upr encoding pairs ----------------------------------------------------

#[test]
fn upr_unicode_pair() {
    let text = extract("rtfparserkit_upr.rtf");
    assert!(text.contains("TEST"), "got: {text}");
    assert!(
        text.contains("License Agreement"),
        "expected license text, got: {text}"
    );
}
