//! Predefined CMap registry for CID font character code decoding.
//!
//! PDF composite fonts use CMaps to map character codes (byte sequences
//! from content streams) to CIDs (character identifiers). This module
//! provides lookup tables for predefined CMaps that the PDF spec requires
//! viewers to support.
//!
//! For text extraction, we need two things from a CMap:
//! 1. **Codespace ranges**: how many bytes per character code
//! 2. **CID-to-Unicode fallback**: when ToUnicode is missing, map CID -> Unicode
//!
//! Identity-H/V are by far the most common in modern PDFs. They use a simple
//! 2-byte identity mapping (character code == CID). When the font also lacks
//! ToUnicode, we try interpreting the CID directly as a Unicode code point,
//! which works for most modern PDF generators.

/// Information about a predefined CMap encoding.
#[derive(Debug, Clone)]
pub struct PredefinedCMap {
    /// CMap name (e.g. "Identity-H").
    pub name: &'static str,
    /// Number of bytes per character code. For variable-length CMaps this
    /// is the maximum; callers must consult codespace ranges.
    pub code_length: u8,
    /// Whether this is a vertical writing CMap.
    pub is_vertical: bool,
    /// Whether character codes map directly to CIDs (identity mapping).
    /// True for Identity-H/V; false for CMaps with explicit code-to-CID tables.
    pub is_identity: bool,
}

/// Look up a predefined CMap by its encoding name.
///
/// Returns `None` for unknown or embedded CMaps (which must be parsed
/// from the PDF's CMap stream).
pub fn lookup_predefined_cmap(name: &str) -> Option<&'static PredefinedCMap> {
    PREDEFINED_CMAPS.iter().find(|cmap| cmap.name == name)
}

/// Whether the given CMap name is a vertical writing CMap.
///
/// Convention: CMap names ending in "-V" are vertical.
pub fn is_vertical_cmap(name: &str) -> bool {
    name.ends_with("-V")
}

/// Try to map a CID to a Unicode character without ToUnicode.
///
/// This is a best-effort heuristic for Identity-H/V encodings where
/// the CID often IS the Unicode code point (very common in modern PDFs
/// generated by Chrome, XeLaTeX, Word, etc.).
///
/// Returns None if the CID doesn't correspond to a valid Unicode scalar.
pub fn cid_to_unicode_fallback(cid: u32, cmap_name: &str) -> Option<char> {
    // For Identity encodings, try direct Unicode interpretation
    if cmap_name.starts_with("Identity") {
        let c = char::from_u32(cid)?;
        // Reject null, C0/C1 control characters (except common whitespace),
        // and Unicode noncharacters (U+FFFE, U+FFFF, etc.)
        if cid == 0 || is_noncharacter(cid) {
            return None;
        }
        if c.is_control() && !matches!(c, '\t' | '\n' | '\r') {
            return None;
        }
        return Some(c);
    }

    // For other known CMaps, direct interpretation is wrong (CIDs are
    // registry-specific). We'd need full CID-to-Unicode tables.
    // Return None to fall back to U+FFFD.
    None
}

/// Check if a code point is a Unicode noncharacter.
/// Noncharacters: U+FFFE, U+FFFF, and U+xFFFE/U+xFFFF for each plane,
/// plus U+FDD0..U+FDEF.
fn is_noncharacter(cp: u32) -> bool {
    (cp & 0xFFFE) == 0xFFFE || (0xFDD0..=0xFDEF).contains(&cp)
}

// Predefined CMaps that we recognize. This covers the common cases
// without embedding multi-megabyte CID-to-Unicode tables.
//
// Identity CMaps (most common in modern PDFs):
//   Identity-H/V: 2-byte codes, code == CID
//
// Adobe-Japan1 CMaps (Japanese):
//   90ms-RKSJ-H/V: Shift-JIS, variable length (1-2 bytes)
//   UniJIS-UTF16-H/V: UTF-16, 2 bytes
//   UniJIS-UCS2-H/V: UCS-2, 2 bytes
//
// Adobe-GB1 CMaps (Simplified Chinese):
//   GBK-EUC-H/V: GBK, variable length (1-2 bytes)
//   UniGB-UTF16-H/V: UTF-16, 2 bytes
//   UniGB-UCS2-H/V: UCS-2, 2 bytes
//
// Adobe-CNS1 CMaps (Traditional Chinese):
//   ETen-B5-H/V: Big5, variable length (1-2 bytes)
//   UniCNS-UTF16-H/V: UTF-16, 2 bytes
//   UniCNS-UCS2-H/V: UCS-2, 2 bytes
//
// Adobe-Korea1 CMaps (Korean):
//   KSCms-UHC-H/V: UHC/EUC-KR, variable length (1-2 bytes)
//   UniKS-UTF16-H/V: UTF-16, 2 bytes
//   UniKS-UCS2-H/V: UCS-2, 2 bytes

static PREDEFINED_CMAPS: &[PredefinedCMap] = &[
    // Identity (most common)
    PredefinedCMap {
        name: "Identity-H",
        code_length: 2,
        is_vertical: false,
        is_identity: true,
    },
    PredefinedCMap {
        name: "Identity-V",
        code_length: 2,
        is_vertical: true,
        is_identity: true,
    },
    // Adobe-Japan1
    PredefinedCMap {
        name: "90ms-RKSJ-H",
        code_length: 2,
        is_vertical: false,
        is_identity: false,
    },
    PredefinedCMap {
        name: "90ms-RKSJ-V",
        code_length: 2,
        is_vertical: true,
        is_identity: false,
    },
    PredefinedCMap {
        name: "UniJIS-UTF16-H",
        code_length: 2,
        is_vertical: false,
        is_identity: false,
    },
    PredefinedCMap {
        name: "UniJIS-UTF16-V",
        code_length: 2,
        is_vertical: true,
        is_identity: false,
    },
    PredefinedCMap {
        name: "UniJIS-UCS2-H",
        code_length: 2,
        is_vertical: false,
        is_identity: false,
    },
    PredefinedCMap {
        name: "UniJIS-UCS2-V",
        code_length: 2,
        is_vertical: true,
        is_identity: false,
    },
    // Adobe-GB1 (Simplified Chinese)
    PredefinedCMap {
        name: "GBK-EUC-H",
        code_length: 2,
        is_vertical: false,
        is_identity: false,
    },
    PredefinedCMap {
        name: "GBK-EUC-V",
        code_length: 2,
        is_vertical: true,
        is_identity: false,
    },
    PredefinedCMap {
        name: "UniGB-UTF16-H",
        code_length: 2,
        is_vertical: false,
        is_identity: false,
    },
    PredefinedCMap {
        name: "UniGB-UTF16-V",
        code_length: 2,
        is_vertical: true,
        is_identity: false,
    },
    PredefinedCMap {
        name: "UniGB-UCS2-H",
        code_length: 2,
        is_vertical: false,
        is_identity: false,
    },
    PredefinedCMap {
        name: "UniGB-UCS2-V",
        code_length: 2,
        is_vertical: true,
        is_identity: false,
    },
    // Adobe-CNS1 (Traditional Chinese)
    PredefinedCMap {
        name: "ETen-B5-H",
        code_length: 2,
        is_vertical: false,
        is_identity: false,
    },
    PredefinedCMap {
        name: "ETen-B5-V",
        code_length: 2,
        is_vertical: true,
        is_identity: false,
    },
    PredefinedCMap {
        name: "UniCNS-UTF16-H",
        code_length: 2,
        is_vertical: false,
        is_identity: false,
    },
    PredefinedCMap {
        name: "UniCNS-UTF16-V",
        code_length: 2,
        is_vertical: true,
        is_identity: false,
    },
    PredefinedCMap {
        name: "UniCNS-UCS2-H",
        code_length: 2,
        is_vertical: false,
        is_identity: false,
    },
    PredefinedCMap {
        name: "UniCNS-UCS2-V",
        code_length: 2,
        is_vertical: true,
        is_identity: false,
    },
    // Adobe-Korea1
    PredefinedCMap {
        name: "KSCms-UHC-H",
        code_length: 2,
        is_vertical: false,
        is_identity: false,
    },
    PredefinedCMap {
        name: "KSCms-UHC-V",
        code_length: 2,
        is_vertical: true,
        is_identity: false,
    },
    PredefinedCMap {
        name: "UniKS-UTF16-H",
        code_length: 2,
        is_vertical: false,
        is_identity: false,
    },
    PredefinedCMap {
        name: "UniKS-UTF16-V",
        code_length: 2,
        is_vertical: true,
        is_identity: false,
    },
    PredefinedCMap {
        name: "UniKS-UCS2-H",
        code_length: 2,
        is_vertical: false,
        is_identity: false,
    },
    PredefinedCMap {
        name: "UniKS-UCS2-V",
        code_length: 2,
        is_vertical: true,
        is_identity: false,
    },
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_lookup_identity_h() {
        let cmap = lookup_predefined_cmap("Identity-H").unwrap();
        assert_eq!(cmap.name, "Identity-H");
        assert_eq!(cmap.code_length, 2);
        assert!(!cmap.is_vertical);
        assert!(cmap.is_identity);
    }

    #[test]
    fn test_lookup_identity_v() {
        let cmap = lookup_predefined_cmap("Identity-V").unwrap();
        assert!(cmap.is_vertical);
        assert!(cmap.is_identity);
    }

    #[test]
    fn test_lookup_unknown() {
        assert!(lookup_predefined_cmap("CustomEmbedded-H").is_none());
    }

    #[test]
    fn test_lookup_japanese() {
        let cmap = lookup_predefined_cmap("UniJIS-UTF16-H").unwrap();
        assert_eq!(cmap.code_length, 2);
        assert!(!cmap.is_identity);
    }

    #[test]
    fn test_is_vertical_cmap() {
        assert!(!is_vertical_cmap("Identity-H"));
        assert!(is_vertical_cmap("Identity-V"));
        assert!(is_vertical_cmap("UniJIS-UTF16-V"));
        assert!(!is_vertical_cmap("UniJIS-UTF16-H"));
    }

    #[test]
    fn test_cid_to_unicode_fallback_identity() {
        // Identity CMaps: CID often equals Unicode code point
        assert_eq!(cid_to_unicode_fallback(0x41, "Identity-H"), Some('A'));
        assert_eq!(
            cid_to_unicode_fallback(0x4E2D, "Identity-H"),
            Some('\u{4E2D}')
        ); // Chinese char
        assert_eq!(cid_to_unicode_fallback(0x20, "Identity-V"), Some(' '));
    }

    #[test]
    fn test_cid_to_unicode_fallback_non_identity() {
        // Non-identity CMaps: can't do direct mapping
        assert_eq!(cid_to_unicode_fallback(0x41, "90ms-RKSJ-H"), None);
        assert_eq!(cid_to_unicode_fallback(0x41, "UniJIS-UTF16-H"), None);
    }

    #[test]
    fn test_cid_to_unicode_fallback_invalid_scalar() {
        // Surrogate range is not a valid Unicode scalar
        assert_eq!(cid_to_unicode_fallback(0xD800, "Identity-H"), None);
        assert_eq!(cid_to_unicode_fallback(0xDFFF, "Identity-H"), None);
        // Beyond Unicode range
        assert_eq!(cid_to_unicode_fallback(0x110000, "Identity-H"), None);
    }

    #[test]
    fn test_cid_to_unicode_fallback_control_chars() {
        // Common whitespace passes through
        assert_eq!(cid_to_unicode_fallback(0x09, "Identity-H"), Some('\t'));
        assert_eq!(cid_to_unicode_fallback(0x0A, "Identity-H"), Some('\n'));
        assert_eq!(cid_to_unicode_fallback(0x0D, "Identity-H"), Some('\r'));
        // Other C0 control chars are rejected
        assert_eq!(cid_to_unicode_fallback(0x01, "Identity-H"), None);
        assert_eq!(cid_to_unicode_fallback(0x08, "Identity-H"), None); // backspace
        assert_eq!(cid_to_unicode_fallback(0x1F, "Identity-H"), None);
        // Null is rejected
        assert_eq!(cid_to_unicode_fallback(0x00, "Identity-H"), None);
        // C1 control chars are rejected
        assert_eq!(cid_to_unicode_fallback(0x80, "Identity-H"), None);
        assert_eq!(cid_to_unicode_fallback(0x9F, "Identity-H"), None);
        // Noncharacters are rejected
        assert_eq!(cid_to_unicode_fallback(0xFFFE, "Identity-H"), None);
        assert_eq!(cid_to_unicode_fallback(0xFFFF, "Identity-H"), None);
        assert_eq!(cid_to_unicode_fallback(0xFDD0, "Identity-H"), None);
        assert_eq!(cid_to_unicode_fallback(0xFDEF, "Identity-H"), None);
        assert_eq!(cid_to_unicode_fallback(0x1FFFE, "Identity-H"), None);
    }

    #[test]
    fn test_all_vertical_cmaps_detected() {
        for cmap in PREDEFINED_CMAPS {
            assert_eq!(
                cmap.is_vertical,
                is_vertical_cmap(cmap.name),
                "CMap {} vertical flag mismatch",
                cmap.name
            );
        }
    }
}
