//! Corpus-based integration tests for XLSX extraction.
//!
//! Runs udoc-xlsx against the synthetic test corpus generated by
//! `tests/xlsx-corpus/scripts/generate_corpus.py` and compares the
//! extracted text against ground truth.
//!
//! Run with: cargo test -p udoc-xlsx --test corpus_test -- --nocapture

use std::fs;
use std::path::PathBuf;

use udoc_core::backend::{FormatBackend, PageExtractor};

/// Root of the xlsx corpus relative to workspace root.
fn corpus_dir() -> PathBuf {
    let workspace = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .to_path_buf();
    workspace.join("tests/xlsx-corpus")
}

fn corpus_files_dir() -> PathBuf {
    corpus_dir().join("corpus")
}

fn gt_dir() -> PathBuf {
    corpus_dir().join("ground-truth")
}

/// Normalize text for comparison: trim trailing whitespace per line,
/// trim trailing empty lines, normalize line endings.
fn normalize(text: &str) -> String {
    let normalized = text.replace("\r\n", "\n");
    let mut lines: Vec<&str> = normalized.split('\n').map(|l| l.trim_end()).collect();
    while lines.last().map(|l| l.is_empty()).unwrap_or(false) {
        lines.pop();
    }
    lines.join("\n")
}

/// Extract text from a single XLSX page.
fn extract_page_text(doc: &mut udoc_xlsx::XlsxDocument, page_idx: usize) -> String {
    let mut page = FormatBackend::page(doc, page_idx).expect("failed to open page");
    page.text().expect("failed to extract text")
}

#[test]
fn corpus_text_extraction() {
    let corpus = corpus_files_dir();
    let gt = gt_dir();

    if !corpus.exists() {
        eprintln!(
            "Corpus not found at {}. Run: python3 tests/xlsx-corpus/scripts/generate_corpus.py",
            corpus.display()
        );
        return;
    }

    let mut xlsx_files: Vec<PathBuf> = fs::read_dir(&corpus)
        .expect("reading corpus dir")
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.extension().map(|e| e == "xlsx").unwrap_or(false))
        .collect();
    xlsx_files.sort();

    assert!(
        !xlsx_files.is_empty(),
        "No XLSX files in corpus dir: {}",
        corpus.display()
    );

    let total = xlsx_files.len();
    let mut passed = 0;
    let mut failed = 0;
    let mut errors = 0;
    let mut failures: Vec<(String, String)> = Vec::new();

    for (i, xlsx_path) in xlsx_files.iter().enumerate() {
        let stem = xlsx_path.file_stem().unwrap().to_string_lossy();

        // Open the XLSX
        let mut doc = match udoc_xlsx::XlsxDocument::open(xlsx_path) {
            Ok(d) => d,
            Err(e) => {
                errors += 1;
                failures.push((stem.to_string(), format!("OPEN ERROR: {e}")));
                continue;
            }
        };

        let page_count = FormatBackend::page_count(&doc);

        // Check for manifest (multisheet)
        let manifest_path = gt.join(format!("{stem}_manifest.txt"));
        let expected_sheets = if manifest_path.exists() {
            let manifest = fs::read_to_string(&manifest_path).unwrap();
            let first_line = manifest.lines().next().unwrap_or("0");
            first_line.parse::<usize>().unwrap_or(0)
        } else {
            1
        };

        if page_count != expected_sheets {
            failed += 1;
            failures.push((
                stem.to_string(),
                format!("PAGE COUNT: expected {expected_sheets}, got {page_count}"),
            ));
            continue;
        }

        let mut file_ok = true;
        for sheet_idx in 0..page_count {
            let gt_file = gt.join(format!("{stem}_sheet{sheet_idx}.txt"));
            if !gt_file.exists() {
                failed += 1;
                failures.push((
                    stem.to_string(),
                    format!("MISSING GT: {}", gt_file.display()),
                ));
                file_ok = false;
                break;
            }

            let expected = fs::read_to_string(&gt_file).unwrap();
            let expected_norm = normalize(&expected);

            let actual = extract_page_text(&mut doc, sheet_idx);
            let actual_norm = normalize(&actual);

            if actual_norm != expected_norm {
                failed += 1;
                // Show first difference
                let exp_lines: Vec<&str> = expected_norm.lines().collect();
                let act_lines: Vec<&str> = actual_norm.lines().collect();
                let mut diff_msg = format!("MISMATCH sheet {sheet_idx}:");

                for (line_no, (e, a)) in exp_lines.iter().zip(act_lines.iter()).enumerate() {
                    if e != a {
                        diff_msg.push_str(&format!(
                            "\n  line {}: expected {:?}\n  line {}:      got {:?}",
                            line_no, e, line_no, a
                        ));
                        break;
                    }
                }
                if exp_lines.len() != act_lines.len() {
                    diff_msg.push_str(&format!(
                        "\n  line count: expected {}, got {}",
                        exp_lines.len(),
                        act_lines.len()
                    ));
                }

                failures.push((stem.to_string(), diff_msg));
                file_ok = false;
                break;
            }
        }

        if file_ok {
            passed += 1;
        }

        if (i + 1) % 1000 == 0 {
            eprintln!(
                "  Progress: {}/{} files ({} passed, {} failed, {} errors)",
                i + 1,
                total,
                passed,
                failed,
                errors
            );
        }
    }

    eprintln!("\n=== XLSX Corpus Test Results ===");
    eprintln!("Total:   {total}");
    eprintln!("Passed:  {passed}");
    eprintln!("Failed:  {failed}");
    eprintln!("Errors:  {errors}");

    if !failures.is_empty() {
        let show = failures.len().min(50);
        eprintln!("\nFirst {show} failures:");
        for (name, msg) in &failures[..show] {
            eprintln!("  {name}: {msg}");
        }
    }

    let pass_rate = if total > 0 {
        (passed as f64 / total as f64) * 100.0
    } else {
        0.0
    };
    eprintln!("\nPass rate: {pass_rate:.1}%");

    // We want >= 95% pass rate minimum, aim for 100%
    assert!(
        pass_rate >= 90.0,
        "Pass rate {pass_rate:.1}% is below 90% threshold ({passed}/{total})"
    );
}
